language: csharp
solution: Titan.sln

notifications:
  email: false
  webhooks:
    urls:
      - https://rainly.herokuapp.com/travis/370181720797872130/QdWybpGUWOaJkVaJXggJled3VqKdOYoh8471GL7lv9iFzVKHyrO0e-58j9AMvVEmcq-x
    on_success: always
    on_failure: always

mono:
  - weekly

install:
  - chmod +x build.sh
script:
  - ./build.sh

cache:
  directories:
    - packages
    - tools
