version: 2
jobs:
  build:
    working_directory: ~/titan
    docker:
      - image: mono:latest
    steps:
      - restore_cache:
          keys:
            - titan-{{ .Branch }}
            - titan-
      - checkout
      - run:
          name: Run build script
          command: |
            ./build.sh
      - save_cache:
          key: titan-{{ .Branch }}
          paths:
            - "~/titan/packages"
            - "~/titan/tools"
      - store_artifacts:
          path: ~/titan/Titan/bin/Release/Titan.exe
          destination: Titan.exe

notify:
  webhooks:
    - url: https://rainly.herokuapp.com/circle/370181720797872130/QdWybpGUWOaJkVaJXggJled3VqKdOYoh8471GL7lv9iFzVKHyrO0e-58j9AMvVEmcq-x
